# simple knative application to display the routed messages
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shipping-international
spec:
  template:
    spec:
      containers:
        -  # This corresponds to
          # https://github.com/knative/eventing-contrib/tree/main/cmd/event_display
          image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:a214514d6ba674d7393ec8448dd272472b2956207acb3f83152d3071f0ab1911
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: shipping-international-trigger
spec:
  broker: default
  filter:
    attributes:
      type: internationalShipping
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: shipping-international
---
# simple knative application to display the routed messages
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shipping-domestic
spec:
  template:
    spec:
      containers:
        -  # This corresponds to
          # https://github.com/knative/eventing-contrib/tree/main/cmd/event_display
          image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:a214514d6ba674d7393ec8448dd272472b2956207acb3f83152d3071f0ab1911
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: shipping-domestic-trigger
spec:
  broker: default
  filter:
    attributes:
      type: domesticShipping
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: shipping-domestic
---
# simple knative application to display the routed messages
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fraud-evaluation
spec:
  template:
    spec:
      containers:
        -  # This corresponds to
          # https://github.com/knative/eventing-contrib/tree/main/cmd/event_display
          image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:a214514d6ba674d7393ec8448dd272472b2956207acb3f83152d3071f0ab1911
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: fraud-evaluation-trigger
spec:
  broker: default
  filter:
    attributes:
      type: fraudEvaluation
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: fraud-evaluation
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: serverless-workflow-order-processing
spec:
  template:
    spec:
      containers:
        - name: serverless-workflow-order-processing
          imagePullPolicy: IfNotPresent
