apiVersion: app.kiegroup.org/v1beta1
kind: KogitoSupportingService
metadata:
  name: explainability
spec:
  serviceType: Explainability
  replicas: 1
  image: quay.io/kiegroup/kogito-explainability:2.44
  infra:
    - kogito-kafka-infra
