version: "3"

services:
  postgres-compose:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/postgresql/data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      - postgres-compose-network
    container_name: postgres-container

  pgadmin-compose:
    image: dpage/pgadmin4:5.0
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.org
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - 8055:80
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
    container_name: pgadmin-container

networks:
  postgres-compose-network:
    driver: bridge