name: Kogito Examples

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - 'docsimg/**'
      - '.ci/jenkins/**'

jobs:
  build-chain:
    concurrency:
      group: pr-${{ matrix.job_name }}_${{ matrix.os }}_${{ matrix.java-version }}_${{ matrix.maven-version }}_${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 180
    strategy:
      matrix:
        job_name: [ kogito-java-examples, kogito-quarkus-examples, kogito-springboot-examples, serverless-workflow-examples, kogito-gradle-examples ]
        os: [ubuntu-latest]
        java-version: [17]
        maven-version: ['3.9.11']
        include:
          - job_name: kogito-java-examples
            repository: incubator-kie-kogito-examples
            env_KOGITO_EXAMPLES_SUBFOLDER_POM: kogito-java-examples/
          - job_name: kogito-quarkus-examples
            repository: incubator-kie-kogito-examples
            env_KOGITO_EXAMPLES_SUBFOLDER_POM: kogito-quarkus-examples/
          - job_name: kogito-springboot-examples
            repository: incubator-kie-kogito-examples
            env_KOGITO_EXAMPLES_SUBFOLDER_POM: kogito-springboot-examples/
          - job_name: serverless-workflow-examples
            repository: incubator-kie-kogito-examples
            env_KOGITO_EXAMPLES_SUBFOLDER_POM: serverless-workflow-examples/
          - job_name: kogito-gradle-examples
            repository: incubator-kie-kogito-examples
            env_KOGITO_EXAMPLES_SUBFOLDER_POM: gradle-examples/
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.job_name }} (${{ matrix.os }} / Java-${{ matrix.java-version }} / Maven-${{ matrix.maven-version }})
    env:
      DEPENDENCY_TREE_FILE: 'mvn_dependency_tree_${{ matrix.job_name }}_${{ matrix.os }}.txt'
    steps:
      - name: Clean Disk Space
        uses: apache/incubator-kie-kogito-pipelines/.ci/actions/ubuntu-disk-space@main
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Support long paths
        if: ${{ matrix.os == 'windows-latest' }}
        uses: apache/incubator-kie-kogito-pipelines/.ci/actions/long-paths@main
      - name: Java and Maven Setup
        uses: apache/incubator-kie-kogito-pipelines/.ci/actions/maven@main
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
      - name: Build Chain
        uses: apache/incubator-kie-kogito-pipelines/.ci/actions/build-chain@main
        env:
          KOGITO_EXAMPLES_SUBFOLDER_POM: ${{ matrix.env_KOGITO_EXAMPLES_SUBFOLDER_POM }}
        with:
          annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          definition-file: https://raw.githubusercontent.com/${GROUP:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/pull-request-config.yaml
      - name: Surefire Report
        uses: apache/incubator-kie-kogito-pipelines/.ci/actions/surefire-report@main
        if: ${{ always() }}
        with:
          report_paths: '**/*-reports/TEST-*.xml'
      - name: Upload Dependency Trees
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: dependency-trees-logs_${{ matrix.job_name }}_${{ matrix.os }}
          path: '**/${{ env.DEPENDENCY_TREE_FILE }}'